### ISSUE TITLE
MySQL client is installed, but "caching_sha2_password" auth plugin is not supported

### ISSUE THREAD

**Issue by mvorisek** [atk4/image#1]
See https://github.com/atk4/data/pull/529#issuecomment-605489818

**Comment by mvorisek** [comment]
@romaninsh The solution seems to be include `mysql:8.0` image here as well

see how: https://adilsoncarvalho.com/creating-multiple-images-from-a-single-dockerfile-3f69254b6137

and then create there file like `start_mysqld.sh` that will call `mysqld &` with these options:
a) `--bind-address="%"`, see https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_bind_address
b) and `--default-authentication-plugin=mysql_native_password`, see https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_default_authentication_plugin
c) + we should include health check there before the start script will exit

We can then start the mysql database with `start_mysqld.sh` anywhere very easily.

**Comment by romaninsh** [comment]
I'm confused - what is the problem we're solving?

**Comment by mvorisek** [comment]
The issue is `mysql` DB/docker service of the latest version (8.0) can not be used in GH actions as from Alpine, we can not connect to it, because the `mysql` client/executable does not support `caching_sha2_password` auth, so we can not connect.

I tried several things to configure `mysql` service before it starts to allow regular auth, but I was not successful.

@romaninsh how to solve this, can you provide an example how to connect to `mysql` 8.0 docker service in GH from PHP/bash?

**Comment by mvorisek** [comment]
issue solved, see https://github.com/atk4/dsql/pull/220
