### ISSUE TITLE
Trigger build/push on Codefresh every week

### ISSUE THREAD

**Issue by mvorisek** [atk4/image#32]
to update php version

**Comment by romaninsh** [comment]
i can set this up easily with a trigger. Will do now. It's a manual change though.

**Comment by romaninsh** [comment]
<img width="297" alt="Screenshot 2021-01-21 at 14 54 27" src="https://user-images.githubusercontent.com/453929/105367643-9123ed80-5bf8-11eb-8049-5acb8ee0b0d2.png">

Added nightly build.

**Comment by mvorisek** [comment]
@romaninsh is it on weekly basis? As we do not want to push completely new images every day!
